# Generated by Django 5.0.6 on 2024-10-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temperature', models.FloatField(max_length=100)),
                ('Humidity', models.FloatField(max_length=100)),
            ],
        ),
    ]
